export enum EnvironmentEnum {
  ENVIRONMENT = 'NEXT_PUBLIC_ENVIRONMENT',
  TOKEN_PREFIX = 'NEXT_PUBLIC_TOKEN_PREFIX',
  DB_URL = 'NEXT_PUBLIC_DB_URL',
  APP_NAME = 'NEXT_PUBLIC_APP_NAME',
  APP_URL = 'NEXT_PUBLIC_APP_NAME',
}
