import React from 'react';

import { NextPage } from 'next';
import Head from 'next/head';

import { Can } from '@context/ability';

import { FeatureCodeEnum } from '@enums/feature';

const Home: NextPage = () => {
  const { FC_ALL } = FeatureCodeEnum;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Can I="read" this={FC_ALL}>
        <span>teste</span>
      </Can>
    </div>
  );
};

export default Home;
